#ifndef MENU_H
#define MENU_H

// Menu group definitions (ie check one of this group and the rest will uncheck)

#define IDM_GROUP_STATE1        0x1000
#define IDM_GROUP_STATE2		0x2000
#define IDM_GROUP_GB1			0x3000
#define IDM_GROUP_GB2		    0x4000
#define IDM_GROUP_SIZE			0x5000
#define IDM_GROUP_BWPALETTE     0x6000
#define IDM_GROUP_MAINFILTER    0x7000
#define IDM_GROUP_BORDERFILTER  0x8000
#define IDM_GROUP_UNL           0x9000
#define IDM_GROUP_FRAMESKIP     0xA000
#define IDM_GROUP_MIXFRAMES     0xB000
#define IDM_GROUP_VOLUME        0xC000
#define IDM_GROUP_LOWPASS       0xD000
#define IDM_GROUP_JOY           0xE000
#define IDM_GROUP_DEVICE        0xF000
#define IDM_GROUP_AUTOFIRE      0x1800
#define IDM_GROUP_GBCSGB        0x2800

// Menu item definitions

#define IDM_FILEOPEN          0x01

#define IDM_FILEOPEN2         0x02
#define IDM_FILECLOSE2        0x03
#define IDM_CPURESET2         0x04
#define IDM_CPUGBA2           IDM_GROUP_GB2 | 0x00
#define IDM_CPUGBC2           IDM_GROUP_GB2 | 0x01
#define IDM_CPUGB2            IDM_GROUP_GB2 | 0x02
#define IDM_CPUGBP2           IDM_GROUP_GB2 | 0x03
#define IDM_CPUAUTO2          IDM_GROUP_GB2 | 0x04
#define IDM_FILEOPENSAMEASGB1 0x05
#define IDM_LOADGB1SAVE       0x06
#define IDM_CPU2STATELOAD     0x07
#define IDM_CPU2STATESAVE     0x08
#define IDM_CPU2STATESLOT0    IDM_GROUP_STATE2 | 0x00
#define IDM_CPU2STATESLOT1    IDM_GROUP_STATE2 | 0x01
#define IDM_CPU2STATESLOT2    IDM_GROUP_STATE2 | 0x02
#define IDM_CPU2STATESLOT3    IDM_GROUP_STATE2 | 0x03
#define IDM_CPU2STATESLOT4    IDM_GROUP_STATE2 | 0x04
#define IDM_CPU2STATESLOT5    IDM_GROUP_STATE2 | 0x05
#define IDM_CPU2STATESLOT6    IDM_GROUP_STATE2 | 0x06 
#define IDM_CPU2STATESLOT7    IDM_GROUP_STATE2 | 0x07
#define IDM_CPU2STATESLOT8    IDM_GROUP_STATE2 | 0x08
#define IDM_CPU2STATESLOT9    IDM_GROUP_STATE2 | 0x09

#define IDM_ROMINFO         0x09
#define IDM_FILECLOSE       0x0a
#define IDM_FILEEXIT        0x0b
#define IDM_FOLDERS         0x0c
#define IDM_CHEATS          0x0d

#define IDM_CPURESET        0x0e
#define IDM_CPUSOFTRESET    0x0f
#define IDM_CPUSOFTRESET2   0x10
#define IDM_CPUPAUSE        0x11
#define IDM_CPUGBA          IDM_GROUP_GB1 | 0x00
#define IDM_CPUGBC          IDM_GROUP_GB1 | 0x01
#define IDM_CPUSGB          IDM_GROUP_GB1 | 0x02
#define IDM_CPUSGB2         IDM_GROUP_GB1 | 0x03
#define IDM_CPUGB           IDM_GROUP_GB1 | 0x04
#define IDM_CPUGBP          IDM_GROUP_GB1 | 0x05
#define IDM_CPUAUTO         IDM_GROUP_GB1 | 0x06
#define IDM_CPUGBCSGB       IDM_GROUP_GBCSGB | 0x00
#define IDM_CPUGBCSGBI      IDM_GROUP_GBCSGB | 0x01
#define IDM_CPUSTATELOAD    0x12
#define IDM_CPUSTATESAVE    0x13
#define IDM_CPUSTATESLOT0   IDM_GROUP_STATE1 | 0x00
#define IDM_CPUSTATESLOT1   IDM_GROUP_STATE1 | 0x01
#define IDM_CPUSTATESLOT2   IDM_GROUP_STATE1 | 0x02
#define IDM_CPUSTATESLOT3   IDM_GROUP_STATE1 | 0x03
#define IDM_CPUSTATESLOT4   IDM_GROUP_STATE1 | 0x04
#define IDM_CPUSTATESLOT5   IDM_GROUP_STATE1 | 0x05
#define IDM_CPUSTATESLOT6   IDM_GROUP_STATE1 | 0x06
#define IDM_CPUSTATESLOT7   IDM_GROUP_STATE1 | 0x07
#define IDM_CPUSTATESLOT8   IDM_GROUP_STATE1 | 0x08
#define IDM_CPUSTATESLOT9   IDM_GROUP_STATE1 | 0x09

#define IDM_CPUSPFS9        0x14
#define IDM_CPUSPSNDOFF     0x15

#define IDM_CPUOPCODE       0x16

#define IDM_OPTIONVIDEOSIZE1    IDM_GROUP_SIZE | 0x00
#define IDM_OPTIONVIDEOSIZE2    IDM_GROUP_SIZE | 0x01
#define IDM_OPTIONVIDEOSIZE3    IDM_GROUP_SIZE | 0x02
#define IDM_OPTIONVIDEOSIZE4    IDM_GROUP_SIZE | 0x03
#define IDM_OPTIONVIDEOBW       IDM_GROUP_BWPALETTE | 0x00
#define IDM_OPTIONVIDEOLCDBROWN IDM_GROUP_BWPALETTE | 0x01
#define IDM_OPTIONVIDEOLCDGREEN IDM_GROUP_BWPALETTE | 0x02
#define IDM_OPTIONVIDEOGRAY     IDM_GROUP_BWPALETTE | 0x03

#define IDM_VIDEOFILTERNONE     IDM_GROUP_MAINFILTER | 0x00
#define IDM_VIDEOFILTERSOFT2X   IDM_GROUP_MAINFILTER | 0x01
#define IDM_VIDEOFILTERSOFTXX   IDM_GROUP_MAINFILTER | 0x02
#define IDM_VIDEOFILTERSCALE2X  IDM_GROUP_MAINFILTER | 0x03
#define IDM_VIDEOFILTERSCALE3X  IDM_GROUP_MAINFILTER | 0x04
#define IDM_VIDEOFILTERBLUR     IDM_GROUP_MAINFILTER | 0x05
#define IDM_VIDEOFILTER5        IDM_GROUP_MAINFILTER | 0x06
#define IDM_VIDEOFILTERUSEMMX   0x2F

#define IDM_VIDEOFILTERBORDERNONE     IDM_GROUP_BORDERFILTER | 0x00
#define IDM_VIDEOFILTERBORDERSOFT2X   IDM_GROUP_BORDERFILTER | 0x01
#define IDM_VIDEOFILTERBORDERSOFTXX   IDM_GROUP_BORDERFILTER | 0x02
#define IDM_VIDEOFILTERBORDERSCALE2X  IDM_GROUP_BORDERFILTER | 0x03
#define IDM_VIDEOFILTERBORDERSCALE3X  IDM_GROUP_BORDERFILTER | 0x04
#define IDM_VIDEOFILTERBORDERBLUR     IDM_GROUP_BORDERFILTER | 0x05
#define IDM_VIDEOFILTERBORDER5        IDM_GROUP_BORDERFILTER | 0x06
#define IDM_OPTIONVIDEOGBCCOLORS      0x2E

#define IDM_OPTIONVIDEOFS0    IDM_GROUP_FRAMESKIP | 0x00
#define IDM_OPTIONVIDEOFS1    IDM_GROUP_FRAMESKIP | 0x01
#define IDM_OPTIONVIDEOFS2    IDM_GROUP_FRAMESKIP | 0x02
#define IDM_OPTIONVIDEOFS3    IDM_GROUP_FRAMESKIP | 0x03
#define IDM_OPTIONVIDEOFS4    IDM_GROUP_FRAMESKIP | 0x04
#define IDM_OPTIONVIDEOFS5    IDM_GROUP_FRAMESKIP | 0x05
#define IDM_OPTIONVIDEOFS6    IDM_GROUP_FRAMESKIP | 0x06
#define IDM_OPTIONVIDEOFS7    IDM_GROUP_FRAMESKIP | 0x07
#define IDM_OPTIONVIDEOFS8    IDM_GROUP_FRAMESKIP | 0x08
#define IDM_OPTIONVIDEOFS9    IDM_GROUP_FRAMESKIP | 0x09
#define IDM_OPTIONVIDEOFSAUTO   0x2D
#define IDM_OPTIONVIDEOENBG     0x17
#define IDM_OPTIONVIDEOENWIN    0x18
#define IDM_OPTIONVIDEOENSPRITE 0x19
#define IDM_OPTIONVIDEOMIXOFF   IDM_GROUP_MIXFRAMES | 0x00
#define IDM_OPTIONVIDEOMIXON    IDM_GROUP_MIXFRAMES | 0x01
#define IDM_OPTIONVIDEOMIXMORE  IDM_GROUP_MIXFRAMES | 0x02

#define IDM_OPTIONVIDEOSPRLIM   0x1A
#define IDM_OPTIONVIDEOLCDOFF   0x1B

#define IDM_OPTIONVIDEOVISUALRUMBLE 0x1C

#define IDM_OPTIONCPUUSAGE      0x1D

#define IDM_OPTIONOPPOSITEDIRECTIONS 0x1E

#define IDM_OPTIONSOUND     0x1F

#define IDM_OPTIONSOUNDENCH1 0x20
#define IDM_OPTIONSOUNDENCH2 0x21
#define IDM_OPTIONSOUNDENCH3 0x22
#define IDM_OPTIONSOUNDENCH4 0x23
#define IDM_OPTIONSOUNDLOWPASS1 IDM_GROUP_LOWPASS | 0x00
#define IDM_OPTIONSOUNDLOWPASS2 IDM_GROUP_LOWPASS | 0x01
#define IDM_OPTIONSOUNDLOWPASSNONE IDM_GROUP_LOWPASS | 0x02
#define IDM_OPTIONSOUNDRSTEREO 0x24

#define IDM_OPTIONSOUNDVOL1 IDM_GROUP_VOLUME | 0x00
#define IDM_OPTIONSOUNDVOL2 IDM_GROUP_VOLUME | 0x01
#define IDM_OPTIONSOUNDVOL3 IDM_GROUP_VOLUME | 0x02
#define IDM_OPTIONSOUNDVOL4 IDM_GROUP_VOLUME | 0x03

#define IDM_OPTIONCONTROL   0x25
#define IDM_OPTIONCONTROL1  0x26
#define IDM_OPTIONCONTROL2  0x27
#define IDM_OPTIONCONTROL3  0x28
#define IDM_OPTIONCONTROL4  0x29

#define IDM_OPTIONSENSOR    0x2A

#define IDM_OPTIONCONTROL_AUTOFIRE_SPEED_SLOW       IDM_GROUP_AUTOFIRE | 0x00
#define IDM_OPTIONCONTROL_AUTOFIRE_SPEED_FASTEST    IDM_GROUP_AUTOFIRE | 0x01
#define IDM_OPTIONCONTROL_AUTOFIRE_SPEED_FAST       IDM_GROUP_AUTOFIRE | 0x02
#define IDM_OPTIONCONTROL_AUTOFIRE_SPEED_MEDIUM     IDM_GROUP_AUTOFIRE | 0x03

#define IDM_OPTIONCONTROLJOY1  IDM_GROUP_JOY | 0x00
#define IDM_OPTIONCONTROLJOY2  IDM_GROUP_JOY | 0x01
#define IDM_OPTIONCONTROLJOY3  IDM_GROUP_JOY | 0x02
#define IDM_OPTIONCONTROLJOY4  IDM_GROUP_JOY | 0x03
#define IDM_OPTIONCONTROLJOYCH  0x2B
#define IDM_HELPABOUT           0x2C

#define IDM_DEVICENONE       IDM_GROUP_DEVICE | 0x00
#define IDM_DEVICEBARCODE    IDM_GROUP_DEVICE | 0x01

#define IDM_UNLAUTO			IDM_GROUP_UNL | 0x00
#define IDM_UNLNIUTOUDE		IDM_GROUP_UNL | 0x01
#define IDM_UNLNONE 		IDM_GROUP_UNL | 0x02
#define IDM_UNLSINTAX		IDM_GROUP_UNL | 0x03

#define WIN32_LEAN_AND_MEAN
#define UNICODE
#include <windows.h>


class menu
{
	public:
		static HMENU menuBar;
		static void checkOption(int option);
		static void uncheckOption(int option);
		menu();
		
	protected:
	    
};


#endif // MENU_H

