/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef GEST_PRIVATE_H
#define GEST_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.11.0"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	11
#define VER_BUILD	0
#define COMPANY_NAME	""
#define FILE_VERSION	"0.1.11.0"
#define FILE_DESCRIPTION	"GEST GB emulator."
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"gest.exe"
#define PRODUCT_NAME	"GEST"
#define PRODUCT_VERSION	"1.1.1"

#endif /*GEST_PRIVATE_H*/
