/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef GEST_PRIVATE_H
#define GEST_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.3.0.349"
#define VER_MAJOR	0
#define VER_MINOR	3
#define VER_RELEASE	0
#define VER_BUILD	349
#define COMPANY_NAME	""
#define FILE_VERSION	"0.3.0.349"
#define FILE_DESCRIPTION	"unGEST GB emulator"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"unGEST.exe"
#define PRODUCT_NAME	"unGEST"
#define PRODUCT_VERSION	"0.3.0.349"

#endif /*GEST_PRIVATE_H*/
